## 2 Dimensional Arrays.

- Used to plot Matrices.
- Game presentation or recording forecast by days by hour


In [18]:
# Daily tempratures

# Day 1 - 11, 15, 10, 6
# Day 2 - 10, 14, 11, 5
# Day 3 - 12, 17, 12, 8
# Day 4 - 15, 18, 114,9

# We use numpy as it works best with these


import numpy as np 

# Stacking 1D arrays on top of each other
# Space(O(mn)) m = rows , n = columns
# Time(O(mn))
# For it to be 2D in needs to be balanced
tDArray =  np.array([[11, 15, 10, 6], [10, 14, 11, 5], [2, 17, 12, 8], [15, 18, 114,9] ])
print(tDArray)

# Adding a column we have to shift every column to the right
# Adding a new row shift all stuff down
print("=======================================")
# axis 0 = Adding row, 1 = column
# the first param after array is the position index to insert
# "0" first column or first row upto len(rows) or len(columns)
newtDArray = np.insert(tDArray, 0, [[1,2,3,4]], axis=0 )
print(newtDArray)

print("=======================================")
# You can also append, for that you only need to provide axis
newtDArray = np.append(tDArray, [[1,2,3,4]], axis=0 )
print(newtDArray)



[[ 11  15  10   6]
 [ 10  14  11   5]
 [  2  17  12   8]
 [ 15  18 114   9]]
[[  1   2   3   4]
 [ 11  15  10   6]
 [ 10  14  11   5]
 [  2  17  12   8]
 [ 15  18 114   9]]
[[ 11  15  10   6]
 [ 10  14  11   5]
 [  2  17  12   8]
 [ 15  18 114   9]
 [  1   2   3   4]]


In [ ]:
# ACCESSING ELEMENTS
import numpy as np 

# Stacking 1D arrays on top of each other
# Space(O(mn)) m = rows , n = columns
# Time(O(mn))
# For it to be 2D in needs to be balanced
tDArray =  np.array([[11, 15, 10, 6], [10, 14, 11, 5], [2, 17, 12, 8], [15, 18, 114,9] ])

# TIME: O(1)
# SPACE: O(1)
def accessElements(array, rowIndex, colIndex):
    # Len returns number of rows since arrays are stacked on top of each other.
    # Index starts from 0
    if rowIndex >= len(array) and colIndex >= len(array[0]):
        print("row or column index out of boundary")
    print(array[rowIndex][colIndex])

accessElements(tDArray, 2, 3)

8


In [ ]:
# TRAVERSING A 2 DIMENSION ARRAY
# Traversing rows one by one since the arrays are stacked on top of each other.
# You can think of it as traversing a single array then moving to the next one.
import numpy as np 

tDArray =  np.array([[11, 15, 10, 6], [10, 14, 11, 5], [2, 17, 12, 8], [15, 18, 114,9] ])

# Time: O(n^2) 2 for loops
# Space: O(1)
def traverse2DArray(array):
    for row in range(len(array)):
        print(f"======== row:{row + 1} =======")
        for col in range(len(array[row])):
            print(array[row][col])

traverse2DArray(tDArray)
        




======== row:1 =======
11
15
10
6
======== row:2 =======
10
14
11
5
======== row:3 =======
2
17
12
8
======== row:4 =======
15
18
114
9


In [ ]:
# SEARCHING A VALUE FROM A 2 DIMENSION ARRAY
# We will use linear search for now.
# Traversing rows one by one since the arrays are stacked on top of each other.
# You can think of it as traversing a single array then moving to the next one until value is matched
import numpy as np 

tDArray =  np.array([[11, 15, 10, 6], [10, 14, 11, 5], [2, 17, 12, 8], [15, 18, 114,9] ])


# Time: O(n^2) 2 for loops
# Space: O(1)
def search2DArray(array, value):
    for row in range(len(array)):
        for col in range(len(array[row])):
            if (value == array[row][col]):
                return f'Index[{row}][{col}]'

search2DArray(tDArray, 114)
        

'Index[3][2]'

In [ ]:
#  DELETION OF COLUMN OR ROW
# New 2D created in memory, then values are copied ommitting the deleted row or column.

# Time O(mn)
import numpy as np 

tDArray =  np.array([[11, 15, 10, 6], [10, 14, 11, 5], [2, 17, 12, 8], [15, 18, 114,9] ])

# axis tracks the column / row
# the other int controls the index of the said axis
newtDArray = np.delete(tDArray, 0, axis = 0)
print(tDArray)
print("========================================")
print(newtDArray)

[[ 11  15  10   6]
 [ 10  14  11   5]
 [  2  17  12   8]
 [ 15  18 114   9]]
[[ 10  14  11   5]
 [  2  17  12   8]
 [ 15  18 114   9]]
